# Generated by Django 4.2.3 on 2023-07-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERP', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='organization',
        ),
    ]
